version: 2
updates:
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies", "rust"]

  - package-ecosystem: gomod
    directory: /go/controlplane
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies", "go"]

  - package-ecosystem: gomod
    directory: /go/planner
    schedule:
      interval: weekly
    labels: ["dependencies", "go"]

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies", "ui"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "ci"
