[package]
name = "purser-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Generated Purser v1 protobuf + gRPC (tonic) types."

[dependencies]
prost = "0.14.4"
prost-types = "0.14.4"
tonic = "0.14.6"
tonic-prost = "0.14.6"

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-build = "0.14.6"
tonic-prost-build = "0.14.6"
