// ---------------------------------------------------------------------------
// Mock of the Gateway's OpenAI-compatible SSE stream (`POST /v1/chat/completions`
// with `stream: true`). It emits tokens with realistic pacing so the playground
// feels live. Phase 2 swaps this transport for a real `fetch`+SSE reader (see
// the commented `sseChatTransport` in ../api/openai.ts) — the UI is untouched.
// ---------------------------------------------------------------------------
import type { ChatCompletionRequest } from '../api/types';
import type { ChatStreamHandlers, ChatTransport } from '../api/openai';

function craftReply(req: ChatCompletionRequest): string {
  const lastUser = [...req.messages].reverse().find((m) => m.role === 'user');
  const prompt = (lastUser?.content ?? '').trim();
  if (!prompt) {
    return 'Ready when you are — ask me anything and I will answer from the model deployed on your cluster.';
  }
  const lower = prompt.toLowerCase();
  if (lower.includes('hello') || lower.includes('ciao') || lower.includes('hi')) {
    return `Hello! I'm running on your private Purser cluster via the model "${req.model}". This is a mocked response in the Phase-1F skeleton, but the streaming path, token pacing and OpenAI-compatible shape are exactly what the real Gateway will use.`;
  }
  if (lower.includes('token') || lower.includes('speed') || lower.includes('tok/s')) {
    return `Decode throughput depends on how the planner split the model across your nodes. The deploy view shows an honest range (min–max tok/s) rather than a single optimistic number, because inter-node link latency and pipeline depth both move the figure.`;
  }
  return `You said: "${prompt}". This reply is generated by the mock backend so you can validate the chat UX end to end. When wired to the real Gateway, the same request hits POST /v1/chat/completions on the model "${req.model}", streamed back token by token over SSE.`;
}

/** Split into word-ish chunks so streaming looks like real token emission. */
function tokenize(text: string): string[] {
  return text.match(/\S+\s*/g) ?? [text];
}

export const mockChatTransport: ChatTransport = {
  stream(req: ChatCompletionRequest, handlers: ChatStreamHandlers) {
    const tokens = tokenize(craftReply(req));
    let i = 0;
    let cancelled = false;

    const onAbort = () => {
      cancelled = true;
      handlers.onDone('stop');
    };
    handlers.signal?.addEventListener('abort', onAbort, { once: true });

    // Small startup delay to mimic prefill, then stream tokens.
    const startupMs = 260;
    const step = () => {
      if (cancelled) return;
      if (i >= tokens.length) {
        handlers.signal?.removeEventListener('abort', onAbort);
        handlers.onDone('stop');
        return;
      }
      handlers.onToken(tokens[i]);
      i += 1;
      // Jittered per-token delay (~18–48ms) to feel like live decoding.
      window.setTimeout(step, 18 + Math.random() * 30);
    };
    window.setTimeout(step, startupMs);
  },
};
