// Command openapi-gen writes the control-plane OpenAPI contract to disk.
//
// The document is generated by server.GenerateOpenAPISpec from the declarative
// route table (server/openapi_registry.go) merged with the curated enrichment
// in server/openapi.base.json. This binary is the `go generate` entry point:
//
//	//go:generate go run ../cmd/openapi-gen -out openapi.json
//
// declared in server/openapi_gen.go, so `go generate ./server/...` (run from
// the server package directory) rewrites server/openapi.json in place. The
// committed openapi.json is embedded into the binary and served verbatim at
// GET /api/v1/openapi.json; a freshness test fails the build if it drifts from
// what this generator produces.
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/purser/purser/go/controlplane/server"
)

func main() {
	out := flag.String("out", "openapi.json", "path to write the generated OpenAPI JSON document")
	flag.Parse()

	spec, err := server.GenerateOpenAPISpec()
	if err != nil {
		fmt.Fprintf(os.Stderr, "openapi-gen: generate: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, spec, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "openapi-gen: write %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "openapi-gen: wrote %s (%d bytes)\n", *out, len(spec))
}
